export enum Role {
    SEDZIA = 'SEDZIA',
    RADCA = 'RADCA',
    PRAWNIK = 'PRAWNIK',
    ADWOKAT = 'ADWOKAT',
    PRACOWNIK_KANCELARII = 'PRACOWNIK_KANCELARII',
    MANAGER = 'MANAGER',
    SPECJALISTA = 'SPECJALISTA',
}