export enum CaseStatus {
    NEW = 'NOWA',
    IN_PROGRESS = 'W_TOKU',
    WAITING_FOR_AUTHORITY = 'OCZEKUJE_NA_INNY_ORGAN',
    REJECTED = 'ODRZUCONA',
    FINISHED = 'ZAKONCZONA',
    ACCEPTED = 'ZAAKCEPTOWANA',
    PENDING_ACCEPTANCE = 'DO_AKCEPTACJI'
}
