export enum CaseType {
    WNIOSEK_O_STWIERDZENIE_NADPLATY = 'WNIOSEK_O_STWIERDZENIE_NADPLATY',
    PRZEKSZTALCENIE_PRAWA_WIECZYSTEGO_UZYTKOWANIA_WE_WLASNOSC = 'PRZEKSZTALCENIE_PRAWA_WIECZYSTEGO_UZYTKOWANIA_WE_WLASNOSC',
}
